export const STORE_RESULT = "STORE_RESULT";
export const STORE_SUGGESTION = "STORE_SUGGESTION";
export const STARRED_THE_WORD = "STARRED_THE_WORD";
export const UNSTARRED_THE_WORD = "UNSTARRED_THE_WORD";
export const WORD_DETAILS_LOADING = "WORD_DETAILS_LOADING";
export const WORD_DETAILS_FETCH_SUCCESS = "WORD_DETAILS_FETCH_SUCCESS";
export const WORD_DETAILS_FETCH_FAILURE = "WORD_DETAILS_FETCH_FAILURE";
