export const STORE_RESULT = "STORE_RESULT";
export const STORE_SUGGESTION = "STORE_SUGGESTION";
export const STARRED_THE_WORD = "STARRED_THE_WORD";
export const UNSTARRED_THE_WORD = "UNSTARRED_THE_WORD";